import random
from colorama import Fore, Back, Style

SCREEN_WIDTH = 16
SCREEN_HEIGHT = 32

FRAME_BCOLOR = Back.BLACK
FRAME_FCOLOR = Fore.RESET

BAR_BCOLOR = Back.GREEN
BAR_FCOLOR = Fore.RESET
BAR_INIT_X = SCREEN_WIDTH//2
BAR_INIT_Y = SCREEN_HEIGHT-3

POWERUPS = ['G', 'S', 'K', 'T', 'F', 'B']
POWERUP_FRAMES = 60
