from colorama import Fore, Back, Style

SCREEN_WIDTH = 32
SCREEN_HEIGHT = 16

SCREEN_BCOLOR = Back.BLACK
SCREEN_FCOLOR = Fore.BLACK

BAR_BCOLOR = Back.GREEN
BAR_FCOLOR = Fore.RESET
BAR_SIZE = 5
BAR_SPEED = 1
BAR_START = (SCREEN_WIDTH//2-2, SCREEN_HEIGHT-4)
BAR_END = (SCREEN_WIDTH//2+2, SCREEN_HEIGHT-4)
